package co.edu.unicauca.distribuidos.core.sop_corba;


/**
* sop_corba/ControladorNotificacionesInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* miércoles 3 de agosto de 2022 10:54:16 PM COT
*/

public interface ControladorNotificacionesInt extends ControladorNotificacionesIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ControladorNotificacionesInt
