module sop_corba{
    interface ControladorNotificacionesInt{
		struct NotificacionDTO{
			string Id;
    	string TipoIdentificacion;
    	double ValorCompra;
    	string LugarCompra;
    	string FechaHora;
    	string MedioPago;
    	string NitEmpresa;		
		};
		
		void registrarNotificacion( in NotificacionDTO objNotificacion);	
    };    	 
};
