package sop_corba.ControladorNotificacionesIntPackage;


/**
* sop_corba/ControladorNotificacionesIntPackage/NotificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* miércoles 3 de agosto de 2022 09:36:16 PM COT
*/

public final class NotificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String Identifiacion = null;
  public String TipoIdentifiacion = null;
  public double ValorCompra = (double)0;
  public String LugarCompra = null;
  public String FechaHora = null;
  public String MedioPago = null;
  public String NitEmpresa = null;

  public NotificacionDTO ()
  {
  } // ctor

  public NotificacionDTO (String _Identifiacion, String _TipoIdentifiacion, double _ValorCompra, String _LugarCompra, String _FechaHora, String _MedioPago, String _NitEmpresa)
  {
    Identifiacion = _Identifiacion;
    TipoIdentifiacion = _TipoIdentifiacion;
    ValorCompra = _ValorCompra;
    LugarCompra = _LugarCompra;
    FechaHora = _FechaHora;
    MedioPago = _MedioPago;
    NitEmpresa = _NitEmpresa;
  } // ctor

} // class NotificacionDTO
